version: "2"
linters:
  enable:
    - errorlint
    - gosec
    - noctx
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - std-error-handling
